update petitions.petition_signature set city_cleaned=city where city_cleaned is null;


update petitions.petition_signature set city_cleaned='Bucuresti' where city_cleaned in ('Buciresti',
'Buuresti',
'Bicuresti',
'Bucharest, Romania',
'Bcuresti',
'Bucurrsti',
'Bucurestii',
'Bucureati',
'Bucuresto',
'Bucuredti',
'Bucuesti',
'Bucuresi',
'Buc.',
'Bucuresri',
'Bucresti',
'Bucureti',
'Bucursti',
'Bucurestu',
'Bucurest',
'Buc',
'B',
'Bucures',
'Bucuresati',
'Bucurescti',
'Bucuresgi',
'Bucuresnti',
'Bucuresru',
'Bucuressti',
'Bucurest.i',
'Bucurest8',
'Bucuresta',
'Bucureste',
'Bucurestgi',
'Bucuresti , Sector 1',
'Bucuresti , Sector 6',
'Bucuresti - Penitenciarul Rahova',
'Bucuresti - Sediul Central',
'Bucuresti . Str.serban Voda 126. Sector4',
'Bucuresti /madrid',
'Bucuresti /s/4',
'Bucuresti E',
'Bucuresti Groza.v@yahoo.ro',
'Bucuresti I',
'Bucuresti Ilfov',
'Bucuresti Q',
'Bucuresti Romania',
'Bucuresti S.4,',
'Bucuresti Sec 1',
'Bucuresti Sect 5',
'Bucuresti Sect.1',
'Bucuresti Sect.6',
'Bucuresti Sector 1',
'Bucuresti Sector 2',
'Bucuresti Sector 3',
'Bucuresti Sector 6',
'Bucuresti Sectorul 1',
'Bucuresti Sectorul 5',
'Bucuresti Str.cozla 8 C ,sector 3',
'Bucuresti Votat Si',
'Bucuresti!',
'Bucuresti,',
'Bucuresti, Bucuresti',
'Bucuresti, Bucuresti Sectorul 3',
'Bucuresti, Bucuresti-Ilfov',
'Bucuresti, Calea Vitan',
'Bucuresti, Judetul Bucuresti-Ilfov',
'Bucuresti, Romania',
'Bucuresti, Sect 3',
'Bucuresti, Sector 2',
'Bucuresti,sector 2',
'Bucuresti-Str. Cozla 8 C  Sector 3',
'Bucuresti.',
'Bucuresti/calarasi',
'Bucuresti/newyork',
'Bucuresti1',
'Bucuresti5',
'Bucuresti9',
'Bucuresti??',
'Bucurestia',
'Bucurestiaiast',
'Bucurestiborzmatilda',
'Bucurestid',
'Bucurestie',
'Bucurestih',
'Bucurestijmantescu',
'Bucurestil',
'Bucurestim',
'Bucurestima',
'Bucurestimastmar',
'Bucurestimi',
'Bucurestimno',
'Bucurestimu',
'Bucurestin',
'Bucurestip',
'Bucurestir',
'Bucurestiromania',
'Bucurestisi',
'Bucurestisilica.iordache',
'Bucurestistelica',
'Bucurestit',
'Bucurestitu',
'Bucurestiu',
'Bucurestiul',
'Bucurestiului',
'Bucurestivasile.urzica',
'Bucurestivera',
'Bucurestj',
'Bucurestk',
'Bucurestki',
'Bucurestl',
'Bucurestoli',
'Bucurestri',
'Bucureststi',
'Bucurestti',
'Bucurestui',
'Bucuresui',
'Bucureswti',
'Bucuresy',
'Bucuresyi',
'Bucuresyo',
'Bucuresyto',
'Bucuretsi',
'Bucuretsti',
'Bucurewsti',
'Bucurewti',
'Bucurezsti',
'Bucurezti',
'Bucurfesti',
'Bucurfxti',
'Bucuriest',
'Bucuristi',
'Bucurosi',
'Bucurrdti',
'Bucurresti',
'Bucurrstin',
'Bucurseti',
'Bucurssti',
'Bucurstie',
'Bucurtsti',
'Bucuruesti',
'Bucururesti',
'Bucurusti',
'Bucurwsti',
'Bucusesti',
'Bucutesti',
'Bucutresti',
'Bucutrst',
'Bucutrsti',
'Bucuuresti',
'Bucvuresti',
'Bucyresti',
'Bucucresti',
'Bucucuresti',
'Bucueati',
'Bucueesti',
'Bucuersti',
'Bucuesto',
'Bucuharest',
'Bucuirest',
'Bucuiresti',
'Bucuirsti',
'Bucupesti',
'Bucur Esti',
'Bucur3sti',
'Bucuraesti',
'Bucuras',
'Bucurasti',
'Bucure',
'Bucure;ti',
'Bucureasti',
'Bucuredto',
'Bucureesti',
'Bucureist',
'Bucureresti',
'Bucurersti',
'Bucurerti',
'Bucurestizecadumk',
'Bucuretti',
'Bu Curesti',
'Bu Uresti',
'Bu Urezti',
'Bu Urssti',
'Bu8curesti',
'Bubcuresti',
'Bubucresti',
'Buburesti',
'Buc Uresti',
'Bucarest',
'Bucaresti',
'Buccuresti',
'Buucresti',
'Buucuresti',
'Buucurestir',
'Buurestic',
'Buuucuresti',
'Buuuresti',
'Buvcuresti',
'Buvuresti',
'Buvutesti',
'Buxuresi',
'Buxuresti',
'Buycuresti',
'Bucharest Romania',
'Bucharest, Bucurestiromania',
'Bucharest, Rom',
'Buchsrest',
'Buchuresti',
'Buciurest',
'Bucjmuresti',
'Bucruresti',
'Buicurest',
'Buicuresti',
'Bukarest',
'Bukuresti',
'Buncresti',
'Buncuresti',
'Burcuresti',
'Bu Curesti',
'Bu Uresti',
'Bu Urezti',
'Bu Urssti',
'Bu8curesti',
'Bubcuresti',
'Bubucresti',
'Buburesti',
'Buc',
'Buc Uresti',
'Buc.',
'Buca',
'Bucarest',
'Bucaresti',
'Buccuresti',
'Bucharest');

update petitions.petition_signature set city_cleaned='Timisoara' where city_cleaned in (
'Timisoata',
'Timisoar',
'Timisora',
'Timsoara',
'Timsoaara',
'Timsioara',
'Timraisoa',
'Timosoara',
'Timiwsoara',
'Timispara',
'Timisosra',
'Timisosda',
'Timisorara',
'Timisor',
'Timisooara',
'Timisoatra',
'Timisoarsa',
'Timisoars',
'Timisoarra',
'Timisoarq',
'Timisoarfa',
'Timisoare',
'Timisoaratudorescu2na@',
'Timisoararadu.nela',
'Timisoaralia',
'Timisoarajoldes.gheorghe@yahoo.com',
'Timisoarai',
'Timisoarac',
'Timisoarab',
'Timisoaraaura_maris',
'Timisoaraana_rachieru@yahoo.com',
'Timisoaraa',
'Timisoara2',
'Timisoara/dumbravita',
'Timisoara, Timis',
'Timisoara, Roumanie',
'Timisoara, Romania',
'Timisoara, Judetul Timis',
'Timisoara Romania',
'Timisoara (romania)',
'Timisoaea',
'Timisoaar',
'Timisoaa',
'Timisoa',
'Timiso',
'Timisnoara',
'Timisioara',
'Timisiara',
'Timisara',
'Timisaora',
'Timisaoara',
'Timiosoara',
'Timiosara',
'Timioara',
'Timidoara',
'Timiasoara',
'Timiaora',
'Timiaoara',
'Timi;oara',
'Timi9soara',
'Timi',
'Tiisoara',
'Tiimsoara',
'Tiimisoara',
'Ti Isoara',
'Tmisoara',
'Tmisioara',
'Tm'

);

update petitions.petition_signature set city_cleaned='Constanta' where city_cleaned in (
'Costanta'
);

update petitions.petition_signature set city_cleaned='Cluj Napoca' where city_cleaned in (
'Clujnapoca','Cluj_napoca','Cluj -Napoca','Cluj-N','Cluj - Napoca','Cluj  Napoca','Cluj- Napoca','Cluj','Cluj-Napoca','`cluj-Napoca',
'Clu Napoca',
'Clu-Napoca',
'Club N',
'Clij',
'Clij Napoca',
'Clij-Napoca',
'Club Napoca',
'Clui-Napoca',
'Cluj  - Napoca',
'Cluj -N',
'Cluj / Kolozsvar / Klausenburg',
'Cluj Mapoca',
'Cluj N',
'Cluj N Apoca',
'Cluj N.',
'Cluj Naoca',
'Cluj Naooca',
'Cluj Naouca',
'Cluj Napaca',
'Cluj Napca',
'Cluj Napica',
'Cluj Napo A',
'Cluj Napoa',
'Cluj Napoc',
'Cluj Napoca (transsilvanien)',
'Cluj Napocaa',
'Cluj Napocac',
'Cluj Napocal',
'Cluj Napocan',
'Cluj Napocaov',
'Cluj Napoce',
'Cluj Napocq',
'Cluj Napocs',
'Cluj Napova',
'Cluj Napoxa',
'Cluj Nappca',
'Cluj Naps Ca',
'Cluj Napuca',
'Cluj Nas',
'Cluj Noca',
'Cluj Npoca',
'Cluj Nspoca',
'Cluj Romania',
'Cluj _ Napoca',
'Cluj*napoca',
'Cluj+napoca',
'Cluj, Rom',
'Cluj,-Napoca',
'Cluj,n'
'Cluj,napoca'
'Cluj-',
'Cluj--Napoca',
'Cluj-N.',
'Cluj-Naoca',
'Cluj-Naooca',
'Cluj-Napca',
'Cluj-Napcoa',
'Cluj-Napica',
'Cluj-Napoa',
'Cluj-Napoaca',
'Cluj-Napoc',
'Cluj-Napoca / Kolozsvar / Klausenburg',
'Cluj-Napoca, Cluj',
'Cluj-Napoca, Romania',
'Cluj-Napocaalexandrina.todoran@',
'Cluj-Napocad',
'Cluj-Napocag',
'Cluj-Napocai',
'Cluj-Napocap',
'Cluj-Napoca`',
'Cluj-Napocs',
'Cluj-Napova',
'Cluj-Napoxa',
'Cluj-Napoza',
'Cluj-Nappca',
'Cluj-Nappoca',
'Cluj-Nclujapoca',
'Cluj-Npoca',
'Cluj-Nspoca',
'Cluj.n',
'Cluj.napoca',
'Cluj/n',
'Cluj/napoca',
'Cluj=napoca',
'Clujn Napoca',
'Clujnapocabotezdoru',
'Cluk',
'Cluk Napoca',
'Cluk-Napoca',
'Clul',
'Clul-N',
'Clun-Napoca',
'Cuj - Napoca',
'Cuj Napoca',
'Cuj-Napoca',
'Cum Napoca'
);

update petitions.petition_signature set city_cleaned='Targu Mures' where city_cleaned in (
'Tgmures','Tg.-Mures','Tg. Mures','Tg-Mures','Targu-Mures','Tg.mures','Tg Mures','Tirgu-Mures','Tirgu Mures','Tragu-Mures','Tragu Mures','Tg Murs',
'Tg Murex','Tg  Mures',
'Tg - Mures',
'Tg .mures',
'Tg Mutes',
'Tg-Nures',
'Tg Muress',
'Tg Mures Jud Mures',
'Tg Mure',
'Tg Ms','Tg- Mures',
'Tg,mures',
'Tg, Mures',
'Tg&gt;mures',
'Tg-Mutes',
'Tg-Muresi',
'Tg-Mured','Tg=mures'
'Tg/mures',
'Tg.mures,',
'Tg.mues',
'Tg.mores',
'Tg..- Mures',
'Tg.-Mure;',
'Tg. Murea',
'Tg=mures',
'Tg/mures',
'Tg.mures,',
'Tg.mues',
'Tg.mores',
'Tg..- Mures',
'Tg.-Mure;',
'Tg. Murea'
);

update petitions.petition_signature set city_cleaned='Drobeta Turnu Severin' where city_cleaned in (
'Dr.tr Severin',
'Tr-Severin',
'Tr. Severin',
'Tr.-Severin',
'Trseverin',
'Tr.severin','Dr.tr. Severin','Drobeta Tr -Severin','Tr Severin','Drobeta Tr. Severin','Dr-Tr-Severin','Turnu Severin','Drobeta-Turnu-Severin','Drobeta Tr.severin','Drobeta Tr Severin','Dr. Tr. Severin','Drobeta-Turnu Severin','Drobeta Turnu-Severin','Dr.tr.severin','Dr Tr Severin',
'Dr  Tr Severin',
'Dr -Tr-Severin',
'Dr Tr  Severin',
'Dr Tr Deverin',
'Dr Tr Sev',
'Dr Tr Sever4in',
'Dr Tr Severim',
'Dr Tr Sevrin',
'Dr Tr Srverin',
'Dr Tr.severin',
'Dr Traian Severin',
'Dr Trseverin',
'Dr Turnu Severin',
'Dr Turnu-Severin',
'Dr&gt;tr&gt;severin',
'Dr,tr,severin',
'Dr,tr.severin',
'Dr-Tr Severin',
'Dr. Tr Severin',
'Dr. Tr.- Severin',
'Dr. Tr.-Severin',
'Dr. Tr.severin',
'Dr. Tr/ Severin',
'Dr. Turnu Severin',
'Dr.-Tr. Severin',
'Dr.-Tr.-Severin',
'Dr.rr. Severin',
'Dr.tr .severin',
'Dr.tr-Severin',
'Dr.tr.-Severin',
'Dr.trseveri',
'Dr.turnu Severin',
'Dr.turnu-Severin',
'Dr.turnu.severin',
'Turn -Severinu',
'Turnu - Severin',
'Turnu -Severin',
'Turnu Sevrin',
'Turnu Sevsrin',
'Turnu-Severin',
'Turnu.severin',
'Turnul.severin',
'Turnuseverin'
);

update petitions.petition_signature set city_cleaned='Ramnicu Valcea' where city_cleaned in (
'Ramicu-Valcea',
'Rm.vilcea',
'Rm.-Valcea',
'Ramnicul Valcea',
'Rm-Valcea',
'Rm Vilcea',
'Rm Valcea',
'Rm. Valcea',
'Rm.valcea',
'Rm. Vilcea',
'Rimnicu Vilcea',
'Ramanicu Valcea',
'Ramicu Valcea',
'Ramnic Valcea',
'Ramnicu  Valcea',
'Ramnicu - Valcea'
'Ramnicu -Valcea',
'Ramnicu Valce',
'Ramnicu Valcea, Jud Valcea',
'Ramnicu Valceaconimoldovan@',
'Ramnicu Valces',
'Ramnicu-Valce',
'Ramnicu-Valcea',
'Ramnicul Vilcea',
'Ramnicuvalcea',
'Ramniu Valcea',
'Ranicu Valcea',
'Rimnicu Valcea',
'Rimnicu Viilcea'

);



update petitions.petition_signature set city_cleaned='Alba Iulia' where city_cleaned in (
'Alba-Iulia',
'Alba',
'Alba  Iulia',
'Alba - Iulia',
'Alba -Iulia',
'Alba Ilia',
'Alba Iualia',
'Alba Iuia',
'Alba Iukia',
'Alba Iula',
'Alba Iuli',
'Alba Iulia',
'Alba Iulia Iu',
'Alba Iulian',
'Alba Iulia`',
'Alba Iulie',
'Alba Iuliq',
'Alba Iulis',
'Alba Iulua',
'Alba Lulia',
'Alba Oiulia',
'Alba Oulia',
'Alba Ulia',
'Alba- Iulia',
'Alba-Iulia,romania',
'Alba-Iuliam',
'Alba=iulia',
'Albaiulia',
'Albas Iulia',
'Alba_iulia',
'Aoba Iulia'
);

update petitions.petition_signature set city_cleaned='Brasov' where city_cleaned in (
'Bv',
'Braosv',
'Braov',
'Bras0v',
'Brasiov',
'Brasiv',
'Braso',
'Brasob',
'Brasoc',
'Brasoov',
'Brasopv',
'Brasov, Brasov',
'Brasov, Judet Brasov',
'Brasov, Romania',
'Brasov/romania',
'Brasovc',
'Brasovromania',
'Brasovtr',
'Brasovv',
'Braspov',
'Brassov',
'Brasv',
'Brasvo'
);

update petitions.petition_signature set city_cleaned='Zlatna' where city_cleaned in (
'Zlatna,jud.alba','Zlatna, Jud. Alba','Zlatna Jud. Alba'
);

update petitions.petition_signature set city_cleaned='Zarnesti' where city_cleaned in (
'Zarnesti\\brasov',
'Zarnesti/brasov',
'Zarnesti.brasov',
'Zarnesti-Brasov',
'Zarnesti- Brasov',
'Zarnesti, Brasov',
'Zarnesti Jud. Brasov',
'Zarnesti Jud Brasov',
'Zarnesti Brasov',
'Zarnesti - Brasov',
'Zarnesti (brasov)',
'Zarnesti'
);

update petitions.petition_signature set city_cleaned='Valul Lui Traian' where city_cleaned in (
'Valul Lui Traian',
'Valu Traian Constanta',
'Valu Traian',
'Valu Luitraian, Constanta',
'Valu Lui Trian',
'Valu Lui Traian-Constanta',
'Valu Lui Traian- Jud.constanta',
'Valu Lui Traian,ct',
'Valu Lui Traian, Jud. Constanta',
'Valu Lui Traian Jud.constants',
'Valu Lui Traian Constanta',
'Valu Lui Traian - Constanta',
'Valu Lui Traian',
'Valu Lui Taian'
);

update petitions.petition_signature set city_cleaned='Victoria' where city_cleaned in (
'Victoria-Bv',
'Victoria-Brasov',
'Victoria-- Brasov',
'Victoria, Bv',
'Victoria Jud.brasovnuticiurea@yahoo.com',
'Victoria Jud.brasov',
'Victoria Brasov',
'Victoria - Brasov',
'Victoria',
'Victori Jud Brasov'
);

update petitions.petition_signature set city_cleaned='Targu Jiu' where city_cleaned in (
'Tg-Jiu',
'Tg. Jiu',
'Targ Jiu',
'Targ-Jiu',
'Targu  Jiu',
'Targu - Jiu',
'Targu -Jiu',
'Targu Jii',
'Targu Jiu Strada Eroilor',
'Targu Jiy',
'Targu Ju',
'Targu-Jiu',
'Targu.jiu',
'Targu0jiu',
'Targujiu',
'Targul Jiu',
'Tg  Jiu',
'Tg - Jiu',
'Tg -Jiu',
'Tg. - Jiu',
'Tg.- Jiu',
'Tg.-Jiu',
'Tg.jiu',
'Tg.jyu',
'Tg/jiu',
'Tg=jiu',
'Tgjiu',
'Tg_jiu',
'Tg Ju',
'Tg Jou',
'Tg Jiy',
'Tg Jiu,gorj',
'Tg Jiu',
'Tg Jii',
'Tg Iju',
'Tragu-Jiu',
'Tg-Jyu',
'Tg-Jui',
'Tg-Jiuj',
'Tg-Jiu-Gorj',
'Tg-Ji',
'Tg--Jiu',
'Tg- Jiu',
'Tg,jiu',
'Tg, Jiu'
);


update petitions.petition_signature set city_cleaned='Balotesti' where city_cleaned in (
'Balotesti   Ilfov',
'Balotesti -Ilfov',
'Balotesti If',
'Balotesti Ilfov',
'Balotesti Jud Ilfov',
'Balotesti(ilfov)',
'Balotesti, Ilfov',
'Balotesti-Ilfov',
'Balotesti. Ilfov',
'Balotesti/ilfov'
);

update petitions.petition_signature set city_cleaned='Baicoi' where city_cleaned in (
'Baicoi   Prahova',
'Baicoi  Jud.  Prahova',
'Baicoi Ph',
'Baicoi, Prahova',
'Baicoi,prahova',
'Baicoi-Ph',
'Baicoi-Prahova',
'Baicoi=prahova'
);


update petitions.petition_signature set city_cleaned='Baia Mare' where city_cleaned in (
'Bai Mare',
'Baiamare',
'Baia   Mare',
'Baia  Mare',
'Baia -Mare',
'Baia ;are',
'Baia Maer',
'Baia Mara',
'Baia Mare          Mm',
'Baia Mare Maramures',
'Baia Mare, 430202',
'Baia Mare, Judetul Maramures',
'Baia Mare, Maramures',
'Baia Mare4',
'Baia Mareica',
'Baia Mareioan',
'Baia Marr',
'Baia Marre',
'Baia Marw',
'Baia Matr',
'Baia Mrar',
'Baia Mre',
'Baia Msre',
'Baia- Mare',
'Baia-Mara',
'Baia-Mare',
'Baia-Mare   Maramures',
'Baia-Matr',
'Baia=mare',
'Baiare Ma',
'Baia_mare',
'Baib-Mare'
);

update petitions.petition_signature set city_cleaned='Breaza' where city_cleaned in (
'Breaza , Judetul Prahova',
'Breaza - Prahova',
'Breaza Ph',
'Breaza Prahova',
'Breaza, Prahova',
'Breaza- Prahova',
'Breaza-Prahova',
'Breaza/prahova',
'Breaza_prahova'
);

update petitions.petition_signature set city_cleaned='Brussels' where city_cleaned in (
'Bruselles',
'Brusels',
'Brussel',
'Brusseles',
'Brusselles',
'Bruxeelles',
'Bruxel',
'Bruxeles',
'Bruxell',
'Bruxelle',
'Bruxelled',
'Bruxelles',
'Bruxelles 5',
'Bruxelless',
'Bruxells',
'Bruselles',
'Brusels',
'Brussel',
'Brusseles',
'Brusselles',
'Brussels',
'Bruxeelles',
'Bruxel',
'Bruxeles',
'Bruxell',
'Bruxelle',
'Bruxelled',
'Bruxelles',
'Bruxelles 5',
'Bruxelles/bucuresti',
'Bruxelless',
'Bruxells'
);

update petitions.petition_signature set city_cleaned='Borsa' where city_cleaned in (
'Borsa',
'Borsa  Mm',
'Borsa , Maramures',
'Borsa Maramures',
'Borsa Mm',
'Borsa, Maramures',
'Borsa,maramures',
'Borsa,mm',
'Borsa-Maramures',
'Borsa...maramures'
);

update petitions.petition_signature set city_cleaned='Campulung Moldovenesc' where city_cleaned in (
'C Lung Mold',
'C Lung Moldovenesc',
'C-Lumg Mold',
'C-Lung Mold.',
'C-Lung Moldovenesc',
'C-Lung-Moldovenesc',
'C-Lung. Mold',
'C-Lung. Moldovenesc',
'C-Lung.mold.',
'C.lung Moldovenesc',
'C.lung.moldovenesc',
'Cimpulung Mold',
'Cimpulung Mold.',
'Cimpulung Moldovenesc',
'Cimpulung-Moldovenesc',
'Cimpulungmoldovenesc',
'Campukung Moldovenesc',
'Campuling Moldovenesc',
'Campulun Moldovenesc',
'Campulung  Mold',
'Campulung  Moldovenesc',
'Campulung Mo0ldovenesc',
'Campulung Mold',
'Campulung Mold.',
'Campulung Moldovenec',
'Campulung Moldovenes',
'Campulung Moldovenesc Suceava',
'Campulung Moldovenessc',
'Campulung Moldovenesx',
'Campulung Moldovenrsc',
'Campulung Moldovnesc',
'Campulung Moldovnesc Jud.suceava',
'Campulung Moldovrnesc',
'Campulung-M.',
'Campulung-Moldovenesc'
);

update petitions.petition_signature set city_cleaned='Codlea' where city_cleaned in (
'Codlea , Brasov',
'Codlea ,brasov',
'Codlea Brasov',
'Codlea Bv',
'Codlea Jud Brasov',
'Codlea Judetul Brasov',
'Codlea, Brasov',
'Codlea, Jud. Brasov',
'Codlea, Judetul Brasov',
'Codlea-Brasov',
'Codleada'
);

update petitions.petition_signature set city_cleaned='Constanta' where city_cleaned in (
'Constants',
'Constantu',
'Constany',
'Constata',
'Constatan',
'Constnata',
'Constnta',
'Constranta',
'Constsnta',
'Constsnts',
'Consttanta',
'Contanta',
'Connstanta',
'Cons',
'Consanta',
'Consatnta',
'Consdtanta',
'Consta',
'Constaanta',
'Constabta',
'Constamta',
'Constan',
'Constan\'a',
'Constana',
'Constanata',
'Constanra',
'Constant',
'Constanta .',
'Constanta Cornel Costea',
'Constanta, Constanta',
'Constanta, Romania',
'Constantac',
'Constantaenachevas',
'Constantaflorindmanea@gmail.com',
'Constantagfrusina',
'Constantanta',
'Constantaq',
'Constantar',
'Constanta`',
'Conztanta',
'Coonstanta',
'Cponstanta'
);

update petitions.petition_signature set city_cleaned='Craiova' where city_cleaned in (
'Craiiova',
'Craiiva',
'Craio0va',
'Craioa',
'Craioav',
'Craioava',
'Craioba',
'Craioca',
'Craiocva',
'Craioiva',
'Craioma',
'Craiov',
'Craiova   Dolj',
'Craiova Elenadumitrescu',
'Craiova, 200640',
'Craiova, Dolj',
'Craiova, Judetul Dolj',
'Craiova,dolj',
'Craiova-Dolj',
'Craiovaa',
'Craiovac',
'Craiovadsiagicasfj',
'Craiovall',
'Craiovas',
'Craiovastr.amilcarsandulescu 5',
'Craiovba',
'Craiovs',
'Craivoa',
'Crajova',
'Craova',
'Craqiova',
'Cratova',
'Criova',
'Crsiova',
'Crsiovs'
);



update petitions.petition_signature set city_cleaned='Curtea De Arges' where city_cleaned in (
'Currea De Arges',
'Curte De Arges',
'Curtea',
'C De Arges',
'C. De Arges',
'C.de Arges',
'C:de Arges',
'Curtea  De  Arges',
'Curtea De A Rges',
'Curtea De Ages',
'Curtea De Ares',
'Curtea De Arged',
'Curtea De Arges, Jud. Arges',
'Curtea De Argesii',
'Curtea De Argez',
'Curtea De Argrges',
'Curtea Dearges',
'Curtea Vde Arges',
'Curtea-De-Arges',
'Curtea. Dearges',
'Curteade Arges',
'Cutea De Arges');

update petitions.petition_signature set city_cleaned='Piatra Neamt' where city_cleaned in (
'Piatra_neamt',
'Piatraneamt',
'Piatraa Neamt',
'Piatra/neamt',
'Piatra-Nemt',
'Piatra-Neamt',
'Piatra-Namt',
'Piatra- Neamt',
'Piatra Niamt',
'Piatra Newamt',
'Piatra Nemt',
'Piatra Nemat',
'Piatra Neeamt',
'Piatra Neant',
'Piatra Neamtpr',
'Piatra Neamta',
'Piatra Neamt, Neamt',
'Piatra Neamt Jud. Neamt',
'Piatra Neamr',
'Piatra Neamnt',
'Piatra Neam',
'Piatra Naemt',
'Piatra Meamt',
'Piatra Eamt',
'Piatra -Neamt',
'Piatra - Neamt',
'Piatra  Neamt',
'Piatra   Neamt',
'Piatra',
'Piatr Neamt',
'Piatea Neamt',
'Piata Neamt',
'P Neamt',
'P Nt',
'P- Neamt',
'P. Neamt',
'P.n',
'P.neamt',
'P;.neamt',
'Pioatra Neamt'
);

update petitions.petition_signature set city_cleaned='Pitesti' where city_cleaned in (
'Pitsti',
'Pitssti',
'Pitseti',
'Pitrsti',
'Pitezti',
'Piteti',
'Pitesyi',
'Pitestu',
'Pitesto',
'Pitestiu',
'Pitestipitesti',
'Pitestie',
'Pitesti.',
'Pitesti-Arges',
'Pitesti, Arges',
'Pitesti\'',
'Pitesti Romania',
'Pitesti Arges',
'Pitest',
'Pitesri',
'Pitesi',
'Pitesfi',
'Pites',
'Pitedto',
'Piteati'
);

update petitions.petition_signature set city_cleaned='Ploiesti' where city_cleaned in (
'Plooesti',
'Ploisti',
'Ploirsti',
'Ploietti',
'Ploieti',
'Ploiestyi',
'Ploiestu',
'Ploiesto',
'Ploiesti`',
'Ploiestisi',
'Ploiestir',
'Ploiestiori',
'Ploiestio',
'Ploiestii',
'Ploiesticom',
'Ploiestib',
'Ploiestiaurelia.petre',
'Ploiesti2',
'Ploiesti-Prahova',
'Ploiesti,prahova',
'Ploiesti, Romania',
'Ploiesti, Prahova',
'Ploiesti - Prahova',
'Ploiest8',
'Ploiest',
'Ploiesri',
'Ploiesi',
'Ploiescti',
'Ploies',
'Ploiersti',
'Ploiedti',
'Ploieati',
'Ploieasti',
'Ploie;ti',
'Ploiasti',
'Ploi',
'Ploesti',
'Ploeisti',
'Plioesti',
'Pliesti'
);

update petitions.petition_signature set city_cleaned='Phoenix' where city_cleaned in (
'Phoenx',
'Phoeniz',
'Phoenix,arizona',
'Phoenix, Az',
'Phoenix, Arizona',
'Phoenix Az',
'Phoenix Arizona',
'Phoenix ,az.',
'Phoenix , Az',
'Phoebix,az',
'Pheonix',
'Phenix - Arizona');

update petitions.petition_signature set city_cleaned='Popesti Leordeni' where city_cleaned in (
'Popestileordeni',
'Popesti-Leordenimargaretacarabageac#@@',
'Popesti-Leordenibucuresti, Sector4',
'Popesti-Leordeni, Ilfov',
'Popesti-Leordeni Ilfov',
'Popesti-Leordeni',
'Popesti-Leorden',
'Popesti-Leordemi',
'Popesti-Leoddeni',
'Popesti-Leirdeni',
'Popestileordeni',
'Popesti-Leordenimargaretacarabageac#@@',
'Popesti-Leordenibucuresti, Sector4',
'Popesti-Leordeni, Ilfov',
'Popesti-Leordeni Ilfov',
'Popesti-Leordeni',
'Popesti-Leorden',
'Popesti-Leordemi',
'Popesti-Leoddeni',
'Popesti-Leirdeni',
'Popesti- Leordeni',
'Popesti Lrordeni',
'Popesti Loerdeni',
'Popesti Leordeni-Ilfov',
'Popesti Leordeni Ilfov',
'Popesti Leordeni - Ilfov',
'Popesti Leoedeni',
'Popesti Leirdeni',
'Popesti -Leordeni',
'Popesti - Leordeni',
'Popesti + Leordeni',
'Pop. Leordeni',
'Pop Leordeni');

update petitions.petition_signature set city_cleaned='Roman' where city_cleaned in (
'Roman/neamt',
'Roman-Neamt',
'Roman-Jud.neamt',
'Roman,neamt',
'Roman,jud.neamt',
'Roman, Romania',
'Roman, Neamt',
'Roman, Jud.neamt',
'Roman \\ Neamt',
'Roman Neamt',
'Roman Jud.neamt',
'Roman Jud Neamt',
'Roman , Neamt',
'Roman  Neamt');

update petitions.petition_signature set city_cleaned='Rosiorii De Vede' where city_cleaned in (
'Rosiroi De Vede',
'Rosiorii-De - Vede',
'Rosiorii+de Vede',
'Rosiorii De Vedr',
'Rosiorii De Vede . Jud. Teleorman',
'Rosiorii De Ved',
'Rosiorii -De-Vede',
'Rosiori-De-Vede',
'Rosiori Vede',
'Rosiori Devede',
'Rosiori De Vede',
'Rosiori  De Vede'
);

update petitions.petition_signature set city_cleaned='Tarnaveni' where city_cleaned in (
'Tarnavni Ju.mures',
'Tarnaveni, Mures',
'Tarnaveni Jud.murea',
'Tirnaveni/mures',
'Tirnaveni');

update petitions.petition_signature set city_cleaned='Turnu Magurele' where city_cleaned in (
'Turnumagurele',
'Turnu=magurele',
'Turnu-Magurele',
'Turnu- Magurele',
'Turnu Mgurele',
'Turnu Magurle',
'Turnu Magurelr',
'Turnu Magurele, Teleorman',
'Turnu Magurele Jud Teleorman',
'Turnu Maguele');

update petitions.petition_signature set city_cleaned='Valenii De Munte' where city_cleaned in (
'Valentin De Munte',
'Valeniu De Munte',
'Valeniide Munte',
'Valenii-De-Munte',
'Valenii De Muntr',
'Valenii De Munte-Prahova',
'Valenii De Munte,ph',
'Valenii De Munte,jud. Ph',
'Valenii De Munte, Jud. Ph',
'Valenii De Munte Prahova',
'Valenii De Munte - Prahova',
'Valenii De Munte  Prahova',
'Valenii  De Munte',
'Valeni De Munte,prahova',
'Valeni De Munte');

update petitions.petition_signature set city_cleaned='Vatra Dornei' where city_cleaned in (
'Vatradornei',
'Vatra-Dornei',
'Vatra Drornei',
'Vatra Dronei',
'Vatra Dorni',
'Vatra Dorneia',
'Vatra -Dornei',
'Vatra - Dornei',
'Vatra  Dornei');



update petitions.petition_signature set city_cleaned='Botosani' where city_cleaned in (
'Botoani',
'Botoasani',
'Botosabi',
'Botosai',
'Botosami',
'Botosan',
'Botosana',
'Botosani',
'Botosani (bt)',
'Botosaniatitieneisi',
'Botosanie',
'Botosanielenaromanelena',
'Botosanio',
'Botosaniu',
'Botosank',
'Botosano',
'Botosanu',
'Botosni',
'Bototani',
'Bototsani',
'Botsani');

update petitions.petition_signature set city_cleaned='Bragadiru' where city_cleaned in (
'Bragadiru',
'Bragadiru - Ilfov',
'Bragadiru, Ilfov',
'Bragadiru-If',
'Bragadiru-Ilfov',
'Bragadiru/ilfov',
'Bragadoru');



update petitions.petition_signature set city_cleaned='Boldesti Scaieni' where city_cleaned in (
'Boldessti-Scaeni',
'Boldesti  Scaeni',
'Boldesti Scaeni',
'Boldesti Scaini',
'Boldesti- Scaeni',
'Boldesti- Scaeni, Jud. Prahova',
'Boldesti-Scaeni',
'Boldesti-Scaeni (prahova)',
'Boldesti-Scaieni',
'Boldesti-Scaieni, Jud Ph',
'Boldesti-Scaieni,prahova',
'Boldesti_scaeni');



update petitions.petition_signature set city_cleaned='Munich' where city_cleaned in ('Munchen','Munichen');

update petitions.petition_signature set city_cleaned='Sebes' where city_cleaned in (
'Sebe',
'Sebed',
'Sebee',
'Sebes  Alba',
'Sebes , Jud. Alba',
'Sebes Alba',
'Sebes Jud Alba',
'Sebes Jud. Alba',
'Sebes, Alba Iulia',
'Sebes, Jud.alba',
'Sebes,alba',
'Sebes- Alba',
'Sebes-Alba');

update petitions.petition_signature set city_cleaned='Slatina' where city_cleaned in (
'Slatina    Jud.olt',
'Slatina   Olt',
'Slatina  Olt',
'Slatina ,olt',
'Slatina - Olt',
'Slatina Olt',
'Slatina, Olt',
'Slatina, Olt, Romania',
'Slatina, Olt.',
'Slatina,olt',
'Slatina- Olt',
'Slatina----Olt',
'Slatina-Olt',
'Slatina-Olt.',
'Slatinaa');

update petitions.petition_signature set city_cleaned='Sibiu' where city_cleaned in (
'Siubiu',
'Sivbiu',
'Siviu',
'Sibbiu',
'Sibi',
'Sibih',
'Sibii',
'Sibiiu',
'Sibiu Mitica1941@gmail.com',
'Sibiu, Sibiu County',
'Sibiu, Str. A.saguna, Nr.8',
'Sibiui',
'Sibuu');

update petitions.petition_signature set city_cleaned='Sighetu  Marmatiei' where city_cleaned in (
'Sighet Marmatie',
'Sighet, Mm',
'Sighetu -Marmatiei',
'Sighetu M',
'Sighetu M.',
'Sighetu Maramatiei',
'Sighetu Marmati',
'Sighetu Marmatie',
'Sighetu Marmatiei',
'Sighetu Marmatieiocluzie@',
'Sighetu-M',
'Sighetu-M.',
'Sighetu-Marmatiei',
'Sighetu-Matmatiei',
'Sighetu-Msrmatiei',
'Sighetul M.',
'Sighetul Marm.',
'Sighetul Marmatiei',
'Sighetul-Marmatiei',
'Sighetumarmatiei');

update petitions.petition_signature set city_cleaned='Sebis' where city_cleaned in (
'Sebis Jud. Arad',
'Sebis Judetul Arad',
'Sebis, Arad',
'Sebis, Jud Ard',
'Sebis, Jud.arad',
'Sebis-Ar');




update petitions.petition_signature set city_cleaned='Hunedoara' where city_cleaned in (
'Humedoara',
'Hundoara',
'Hunediara',
'Hunedoaa',
'Hunedoaea',
'Hunedoar',
'Hunedoare',
'Hunedoars',
'Hunedoata',
'Hunedora',
'Hunefoara',
'Hunesoara'
);


update petitions.petition_signature set city_cleaned='Knokke Heist' where city_cleaned in (
'Knokke Heist',
'Knokke- Heist',
'Knokke-Heist',
'Knomke Heist'
);

update petitions.petition_signature set city_cleaned='Londra' where city_cleaned in (
'Londa',
'Londea',
'London',
'London, Greater London',
'Londr',
'Londra(bacau)',
'Londra, Londra Mare',
'Londrla',
'Londrs',
'Londta',
'Lonfon'
);


update petitions.petition_signature set city_cleaned='Lupeni' where city_cleaned in (
'Lupebi',
'Lupeni  Hd',
'Lupeni (hunedoara)',
'Lupeni -Hd',
'Lupeni Hd',
'Lupeni Hunedoara',
'Lupeni Judetul Hunedoara',
'Lupeni,hd.',
'Lupeni-Hunedoara',
'Lupeni. Hd.',
'Lupeni/hd',
'Lupeni/hunedoara',
'Lupeni;hd'
);

update petitions.petition_signature set city_cleaned='Miercurea Ciuc' where city_cleaned in (
'M Ciuc',
'M-Ciuc',
'M-Cuc',
'M.ciuc',
'Miercurea',
'Miercurea  Ciuc',
'Miercurea  Iuc',
'Miercurea Ciuc',
'Miercurea Ciuc, Romania',
'Miercurea Ciuv',
'Miercurea Cuc',
'Miercurea-Ciuc',
'Miercurea-Cuc',
'Miercurea-\\ciuc',
'Miercureaciuc'
);

update petitions.petition_signature set city_cleaned='Mioveni' where city_cleaned in (
'Mioveni  Arges',
'Mioveni - Arges',
'Mioveni Arges',
'Mioveni, Judetul Arges',
'Mioveni,arges',
'Mioveni-Arges',
'Miovni'
);

update petitions.petition_signature set city_cleaned='Moinesti' where city_cleaned in (
'Moines',
'Moinesti - Bacau',
'Moinesti Bacau',
'Moinesti, Bacau',
'Moinesti, Jud. Bacau',
'Moinesti,jud. Bacau',
'Moinesti-Bacau',
'Moinsti'
);

update petitions.petition_signature set city_cleaned='Moldova Noua' where city_cleaned in (
'Moldova  Noua',
'Moldova -Noua',
'Moldova Noia',
'Moldova Nou',
'Moldova Noua      Cs',
'Moldova Noua .cs.',
'Moldova-Noua'
);

update petitions.petition_signature set city_cleaned='Navodari' where city_cleaned in (
'Navodai',
'Navodar',
'Navodar/constanta',
'Navodari Constanta',
'Navodari Jud Constanta',
'Navodari, Constanta',
'Navodari/constanta',
'Navodarii',
'Navodari[jud. Constanta].',
'Navodarj'
);

update petitions.petition_signature set city_cleaned='Odobesti' where city_cleaned in (

'Odobesti   Vrancea',
'Odobesti - Vrancea',
'Odobesti / Vrancea',
'Odobesti Dambovita',
'Odobesti Vrancea',
'Odobesti,vn',
'Odobesti-Vrancea'
);
update petitions.petition_signature set city_cleaned='Odorheiu Secuiesc' where city_cleaned in (
'Odorheiu - Secuiesc',
'Odorheiu -Secuiesc',
'Odorheiu Sec.',

'Odorheiu-Secuiesc',
'Odorheiul Secuiesc'
);
update petitions.petition_signature set city_cleaned='Oltenita' where city_cleaned in (
'Oltemita',

'Oltenita - Calarasi',
'Oltenita Jud Calarasi',
'Oltenita Jud. Calarasi',
'Oltenita, Calarasi',
'Oltenita, Jud. Calarasi',
'Oltenita, Jud.calarasi',
'Oltenita,calarasi'
);
update petitions.petition_signature set city_cleaned='Onesti' where city_cleaned in (
'Onesi',
'Onesrt',
'Onest',

'Onesti    Bacau',
'Onesti -Bacau',
'Onesti Bacau',
'Onesti Jud.bacau.',
'Onesti,  Jud   Bacau',
'Onesti, Jud. Bacau',
'Onesti,bacau',
'Onesti,jud:bacau',
'Onesti- Bacau',
'Onesti--Incinta Bl.26-Bd.oituz',
'Onesti-Bacau',
'Onesti/ Bacau',
'Onesti`',
'Onezti',
'Onsti'
);
update petitions.petition_signature set city_cleaned='Oradea' where city_cleaned in (
'Orada',
'Oradae',
'Oradda',
'Oraddea',
'Orade',

'Oradea Str.vladeasa Nr.29 Bloc D15 , Ap.7',
'Oradea, Bh',
'Oradea, Bihor',
'Oradea,str. Dobrestilor Nr.3 Ap.15',
'Oradeaa',
'Oradeaago',
'Oradeaf',
'Oradeam',
'Oradeama',
'Oradeao',
'Oradeapp',
'Oradeav',
'Oradra',
'Oradrea',
'Oradsa',
'Oraea',
'Orafea',
'Orasea',
'Ordea'
);
update petitions.petition_signature set city_cleaned='Ovidiu' where city_cleaned in (

'Ovidiu   - Constanta',
'Ovidiu  -Constanta',
'Ovidiu -Constanta',
'Ovidiu Jud Constanta',
'Ovidiu, Jud. Constanta',
'Ovidiu- Constanta',
'Ovidiu-Constanta',
'Ovidiu-Jud.constanta',
'Ovidiu/constanta'
);
update petitions.petition_signature set city_cleaned='Rodna' where city_cleaned in (

'Rodna Bistrita-Nasaud',
'Rodna, Bistrita Nasaud',
'Rodna,bistrita-Nasaud',
'Rodna-B.n',
'Rodna-Bisrita'
);
update petitions.petition_signature set city_cleaned='Rosu' where city_cleaned in (

'Rosu / Chiajna',
'Rosu / Chiajna / Ilfov',
'Rosu / Ilfov',
'Rosu Chiajna',
'Rosu, Chiajna',
'Rosu, Jud. Ilfov',
'Rosu,chiajna,ilfov',
'Rosu-Chiajna, Ilfov',
'Rosu/chiajna',
'Rosu/chiajna/ilfov'
);
update petitions.petition_signature set city_cleaned='Sacele' where city_cleaned in (

'Sacele  Brasov',
'Sacele - Brasov',
'Sacele -Brasov',
'Sacele Brasov',
'Sacele Jud. Brasov',
'Sacele Jud.brasov',
'Sacele, Brasov',
'Sacele, Jud. Brasov',
'Sacele,brasov',
'Sacele-Brasov',
'Sacele-Bv',
'Sacele.brasov',
'Sacele/brasov',
'Sacele_brasov'
);
update petitions.petition_signature set city_cleaned='Sacramento' where city_cleaned in (

'Sacramento Ca',
'Sacramento California',
'Sacramento, Ca',
'Sacramento, California',
'Sacramento,california',
'Sacramneto',
'Sacranento'
);
update petitions.petition_signature set city_cleaned='Sannicolau Mare' where city_cleaned in (
'Sanncicolau Mare',
'Sannicolau  Mare',

'Sannicolau Mare  Timis',
'Sannicolau Mare-Timis',
'Sannicolau- Mare',
'Sannicolau-Mare',
'Sannicolaul Mare',
'Sannicolaul Mare Timis',
'Sannicolaul- Mare',
'Sannicolu Mare',
'Sannicolu-Mare',
'Sanniolaul Mare'
);
update petitions.petition_signature set city_cleaned='Stuttgart' where city_cleaned in (
'Sturttgarr',
'Stuttgardt',

'Stuttgart, Deu',
'Stuttugart'
);
update petitions.petition_signature set city_cleaned='Suceava' where city_cleaned in (
'Sucaeva',
'Sucava',
'Suce',
'Sucea A',
'Suceaa',
'Suceaba',
'Suceaca',
'Suceav',

'Suceavac',
'Suceavas',
'Suceavs',
'Sucesva',
'Sucesvs',
'Suceva',
'Sucrava'
);
update petitions.petition_signature set city_cleaned='Targoviste' where city_cleaned in (
'Targiviste',
'Targivuste',
'Targo',
'Targoiste',
'Targoste',
'Targovidste',
'Targovidte',
'Targovise',
'Targovisrr',
'Targovist',
'Tirgiviste',
'Tirgoviste',
'Targoviste Dambovita',
'Targoviste, Dambovita',
'Targoviste- Dambovita',
'Targovisteme',
'Targovister',
'Targovistr',
'Targovistte',
'Targovistw',
'Targovite',
'Targovitste',
'Targovoste',
'Targovviste',
'Targuviste'
);
update petitions.petition_signature set city_cleaned='Targu Mures' where city_cleaned in (
'Targ-Mures',
'Targi-Mures',
'Targu - Mures',
'Targu -Mures',
'Targu M',
'Targu Mires',
'Targu Mjres',
'Targu Mues',
'Targu Murea',
'Targu Mured',

'Targu Mures, Judetul Mures',
'Targu Mures, Mures',
'Targu Mures/marosvasarhely',
'Targu Murescrisstine',
'Targu Murres',
'Targu Murrs',
'Targu+mures',
'Targu-Muire$',
'Targu-Mured',
'Targu-Mures Mures',
'Targu-[mures',
'Targul Mures',
'Targumures',
'Tg_mures',
'Tirgu Mured',
'Tirgu- Mures'
);
update petitions.petition_signature set city_cleaned='Tomesti' where city_cleaned in (

'Tomesti - Iasi',
'Tomesti Iasi',
'Tomesti Jud. Iasi',
'Tomesti, Iasi',
'Tomesti, Jud. Iasi',
'Tomesti,jud Iasi',
'Tomesti-Iasi'
);
update petitions.petition_signature set city_cleaned='Toplita' where city_cleaned in (

'Toplita Harghita',
'Toplita Hr',
'Toplita, Harghita',
'Toplita, Jud. Harghita.',
'Toplits'
);
update petitions.petition_signature set city_cleaned='Madrid' where city_cleaned in (
'Madid',
'Madr6',
'Madrd',
'Coslada',
'Coslada, Madrid',
'Coslada,madrid',
'Coslada-Madrid',
'Madrid/constanta',
'Madridul De Jos',
'Madriz',
'Madrod',
'Madrrid'
);
update petitions.petition_signature set city_cleaned='Miercurea Ciuc' where city_cleaned in (
'M Ciuc',
'M-Ciuc',
'M-Cuc',
'M.ciuc',
'Miercrea Ciuc',
'Miercurea',
'Miercurea  Ciuc',
'Miercurea  Iuc',
'Miercurea Ciuc, Romania',
'Miercurea Ciuv',
'Miercurea Cuc',
'Miercurea-Ciuc',
'Miercurea-Cuc',
'Miercurea-\\ciuc',
'Miercureaciuc'
);
update petitions.petition_signature set city_cleaned='Braila' where city_cleaned in (
'Braial',
'Braiala',
'Brail',

'Braila-Romania',
'Braila.',
'Brailaa',
'Brails',
'Brala',
'Bralia'
);
update petitions.petition_signature set city_cleaned='Bumbesti Jiu' where city_cleaned in (
'Bumbest-Jiu',
'Bumbesti',

'Bumbesti-Jiu',
'Bumbesti-Jiu,gorj',
'Bumbestu-Jiu',
'Bummesti Jiu',
'Bumnbesti - Jiu'
);
update petitions.petition_signature set city_cleaned='Campia Turzii' where city_cleaned in (
'Campia  Turzii',
'Campia -Turzii',
'Campia Turzi',

'Campia Turzii ,cluj',
'Campia Turzii, Jud. Cluj',
'Campia Turzii, Romania',
'Campia Turzii/cluj',
'Campia Turzii/jud.cluj',
'Campia Turzik',
'Campia Tutzii',
'Campia Tuzii',
'Campia- Turzii',
'Campia-Turzii',
'Campiaturzii',
'Cimpia',
'Cimpia  Turzii',
'Cimpia  Turziiandronache',
'Cimpia Turzii',
'Cimpia-Turzii'
);

update petitions.petition_signature set city_cleaned='Campulung' where city_cleaned in (
'Campu Lung',
'Campu Lung Muscel',
'Campullung Muscel',
'Campulug Arges',
'Campulumg',

'Campulung  Arges',
'Campulung  Muscel',
'Campulung - Arges',
'Campulung - Muscel',
'Campulung Ag',
'Campulung Ag.',
'Campulung Arges',
'Campulung Mescel'
'Campulung Musce',
'Campulung Muscel',
'Campulung Muscel,jud.arges',
'Campulung Muscl',
'Campulung Musel',
'Campulung Mustcel',
'Campulung, Arges',
'Campulung, Jud. Arges',
'Campulung,arges',
'Campulung-Arges',
'Campulung-Argesi',
'Campulung-Muscel',
'Campulung-Muscel, Arges',
'Campulung/arges',
'Campulungmuscel',
'Canpulung Muscel',
'Cimpulung',
'Cimpulung Arges',
'Cimpulung Muscel',
'Cimpulung- Arges',
'Cimpulung-Arges',
'Cimpulung/arges',
'Cimpulungi'
);



update petitions.petition_signature set city_cleaned='Resita' where city_cleaned in (
'Resita C-S',
'Resita Caras Severin',
'Resita-Caras-Severin',
'Resita7',
'Resitaa',
'Resitag',
'Resitaq',
'Resitta',
'Resota',
'Resuta'
);

update petitions.petition_signature set city_cleaned='Ramnicu Sarat' where city_cleaned in (
'Ramnic Sarat',
'Ramnicl Sarat',
'Ramnicu  Sarat',
'Ramnicu -Sarat',
'Ramnicu Sarat Buzau',
'Ramnicu Sarat, Judetul Buzau',
'Ramnicu Sarst',
'Ramnicu-Sarat',
'Ramnicul Sarat',
'Rimnicu Sara',
'Rimnicu Sarat',
'Rimnicu Sarat/buzau',
'Rimnicu-Sarat',
'Rimnicu.sarat',
'Rimnicu_sarat'
);


update petitions.petition_signature set city_cleaned='Iasi' where city_cleaned in (
'Iaasi',
'Ias',
'Ias9',
'Iasi (iasi)',
'Iasi,',
'Iasi, Iasi',
'Iasi, Iasi, Romania',
'Iasi, Romania',
'Iasi,is',
'Iasi-',
'Iasi1',
'Iasi8',
'Iasi`',
'Iasj',
'Iassi'
);



update petitions.petition_signature set city_cleaned='Beclean' where city_cleaned in (
'Beclea',
'Becleam',
'Beclean Bn',
'Beclean Judet Bistrita-N',
'Beclean Judet Bistrita-Nr',
'Beclean Pe Somes',
'Beclean,bistrita'
);

update petitions.petition_signature set city_cleaned='Bat Yam' where city_cleaned in (
'Bat -Yam',
'Bat-Yam'
);
update petitions.petition_signature set city_cleaned='Bascov' where city_cleaned in (
'Bascov -Arges',
'Bascov / Arges',
'Bascov Arges',
'Bascov, Arges',
'Bascov,arges',
'Bascov,jud Arges',
'Bascov-Arges'
);
update petitions.petition_signature set city_cleaned='Bals' where city_cleaned in (
'Bals  Jud. Olt',
'Bals - Olt',
'Bals Olt',
'Bals, Olt',
'Bals-Olt'
);
update petitions.petition_signature set city_cleaned='Balcesti' where city_cleaned in (
'Balcesti,  Jud. Valcea',
'Balcesti, Jud.valcea.',
'Balcesti, Valcea',
'Balcesti,valcea',
'Balcesti-Valcea'
);
update petitions.petition_signature set city_cleaned='Bailesti' where city_cleaned in (
'Bailedti',
'Bailesti  Dolj',
'Bailesti, Dolj',
'Bailesti,dolj',
'Bailesti,jud Dolj Str Ai Cuza Nr 1 Bloc 5 Sc 1 Ap4',
'Bailesti-Dolj',
'Bailesti.dolj'
);
update petitions.petition_signature set city_cleaned='Baia de Aries' where city_cleaned in (
'Baia De Aries',
'Baia De Aries , Jud. Alba',
'Baia De Aries Alba',
'Baia De Aries, Jud. Alba'
);
update petitions.petition_signature set city_cleaned='Azuqueca de Henares' where city_cleaned in (
'Azugueca De Henares',
'Azuqeca De Henares',
'Azuqueca De Henares',
'Azuqueca Henares'
);
update petitions.petition_signature set city_cleaned='Atlanta' where city_cleaned in (
'Atlanda  Ga',
'Atlanta  Georgia',
'Atlanta , Georgia 30306',
'Atlanta ,georgia',
'Atlanta Ga',
'Atlanta Georgia',
'Atlanta, Ga',
'Atlanta,ga',
'Atlanta-Ga'
);
update petitions.petition_signature set city_cleaned='Atena' where city_cleaned in (
'Athena',
'Athens',
'Athina'
);
update petitions.petition_signature set city_cleaned='Arlington Heights' where city_cleaned in (
'Arlington Heighst, Ilinois',
'Arlington Heights , Illinois'
);
update petitions.petition_signature set city_cleaned='Arganda del Rey' where city_cleaned in (
'Argabda Del Rey',
'Argand Del Rey',
'Arganda',
'Arganda De Rey',
'Arganda Del  Rey',
'Arganda Del Rey'
);
update petitions.petition_signature set city_cleaned='Antwerp' where city_cleaned in (
'Antterpren',
'Antwerpen',
'Anverpen',
'Anvers',
'Anweiller',
'Anwerpen'
);
update petitions.petition_signature set city_cleaned='Aiud' where city_cleaned in (
'Aiud Alba',
'Aiud Jud Alba',
'Aiud-Alba',
'Aiud-Ciumbrud',
'Aiud-Jud. Alba'
);


update petitions.petition_signature set city_cleaned='Corbeanca' where city_cleaned in (
'Corbeanca , Ilfov',
'Corbeanca - Ilfov',
'Corbeanca - Jud Ilfov',
'Corbeanca Ilfov',
'Corbeanca, Ilfov'
);

update petitions.petition_signature set city_cleaned='Cornetu' where city_cleaned in (
'Cornetu .if',
'Cornetu Ilfov',
'Cornetu Jud Ilfov',
'Cornetu, Ilfov',
'Cornetu- Ilfov',
'Cornetu-Ilfov'
);
update petitions.petition_signature set city_cleaned='Cristian' where city_cleaned in (
'Cristian Brasov',
'Cristian Brsov',
'Cristian Bv',
'Cristian, Brasov',
'Cristian, Judet Brasov'
);

update petitions.petition_signature set city_cleaned='Targu Ocna' where city_cleaned in (
'Targu Ocna - Bacau',
'Targu Ocna,bacau',
'Targu- Ocna',
'Targu-Ocna',
'Tg Ocna',
'Tg Ocna Bacau',
'Tg Ocna Jud Bacau',
'Tg, Ocna',
'Tg-Ocna',
'Tg.  Ocna',
'Tg. Ocna',
'Tg. Ocna-Bacau',
'Tg.ocna',
'Tg/ocna',
'Tirgu-Ocna',
'Tgocna'
);

update petitions.petition_signature set city_cleaned='Targu Frumos' where city_cleaned in (
'Targu Frumos (iasi)',
'Targu Frumos - Iasi',
'Targu Frumos Iasi',
'Targu-Frumos,iasi,romania',
'Tg Frumos',
'Tg Frumos Iasi',
'Tg, Frumos',
'Tg-Frumos',
'Tg. Frumos',
'Tg. Frumos , Jud.iasi',
'Tg. Frumos, Iasi',
'Tg. Frumos, Jud Iasi',
'Tg.frumos',
'Tg.frumos Jud. Iasi',
'Tg.frumos,iasi'
);

update petitions.petition_signature set city_cleaned='Sangeorz Bai' where city_cleaned in (
'Singeoez Bai',
'Singeorz Bai',
'Singeorz- Bai',
'Singeorz-Bai',
'Singeorz/bai',
'Singeorzan Bai',
'Singeorzbai',
'Singeroz-Bai',
'Sangeorz Bai',
'Sangeorz-Bai Bistrita',
'Sangeorz-Bai, Bistrita'
);

update petitions.petition_signature set city_cleaned='Simleu Silvaniei' where city_cleaned in (
'Simlei Silvaniei',
'Simleu',
'Simleu  Silvaniei',
'Simleu -Silvaniei',
'Simleu S',
'Simleu Silvaiei',
'Simleu Silvaniri',
'Simleu-Silv.',
'Simleu-Silvaniei',
'Simleul -Silvsniei',
'Simleul Silvaniei',
'Simleul-Silvaniei',
'Simlei Silvaniei',
'Simleu',
'Simleu  Silvaniei',
'Simleu -Silvaniei',
'Simleu S',
'Simleu Silvaiei',
'Simleu Silvaniri',
'Simleu-Silv.',
'Simleu-Silvaniei',
'Simleul -Silvsniei',
'Simleul Silvaniei',
'Simleul-Silvaniei'

);

update petitions.petition_signature set city_cleaned='Breaza' where city_cleaned in (
'Breaza , Judetul Prahova',
'Breaza - Prahova',
'Breaza Ph',
'Breaza Prahova',
'Breaza, Prahova',
'Breaza- Prahova',
'Breaza-Prahova',
'Breaza/prahova',
'Breaza_prahova'
);

update petitions.petition_signature set city_cleaned='Sighisoara' where city_cleaned in (
'Sighioara',
'Sighisaora',
'Sighisiara',
'Sighisoara',
'Sighisoarapapilon',
'Sighisoata',
'Sighisora',
'Sighsoara',
'Sigisoara'
);