update petitions.petition_signature set city='Bucuresti' where city in ('Buciresti',
'Buuresti',
'Bicuresti',
'Bucharest, Romania',
'Bcuresti',
'Bucurrsti',
'Bucurestii',
'Bucureati',
'Bucuresto',
'Bucuredti',
'Bucuesti',
'Bucuresi',
'Buc.',
'Bucuresri',
'Bucresti',
'Bucureti',
'Bucursti',
'Bucurestu',
'Bucurest',
'Buc',
'B',
'Bucures',
'Bucuresati',
'Bucurescti',
'Bucuresgi',
'Bucuresnti',
'Bucuresru',
'Bucuressti',
'Bucurest.i',
'Bucurest8',
'Bucuresta',
'Bucureste',
'Bucurestgi',
'Bucuresti , Sector 1',
'Bucuresti , Sector 6',
'Bucuresti - Penitenciarul Rahova',
'Bucuresti - Sediul Central',
'Bucuresti . Str.serban Voda 126. Sector4',
'Bucuresti /madrid',
'Bucuresti /s/4',
'Bucuresti E',
'Bucuresti Groza.v@yahoo.ro',
'Bucuresti I',
'Bucuresti Ilfov',
'Bucuresti Q',
'Bucuresti Romania',
'Bucuresti S.4,',
'Bucuresti Sec 1',
'Bucuresti Sect 5',
'Bucuresti Sect.1',
'Bucuresti Sect.6',
'Bucuresti Sector 1',
'Bucuresti Sector 2',
'Bucuresti Sector 3',
'Bucuresti Sector 6',
'Bucuresti Sectorul 1',
'Bucuresti Sectorul 5',
'Bucuresti Str.cozla 8 C ,sector 3',
'Bucuresti Votat Si',
'Bucuresti!',
'Bucuresti,',
'Bucuresti, Bucuresti',
'Bucuresti, Bucuresti Sectorul 3',
'Bucuresti, Bucuresti-Ilfov',
'Bucuresti, Calea Vitan',
'Bucuresti, Judetul Bucuresti-Ilfov',
'Bucuresti, Romania',
'Bucuresti, Sect 3',
'Bucuresti, Sector 2',
'Bucuresti,sector 2',
'Bucuresti-Str. Cozla 8 C  Sector 3',
'Bucuresti.',
'Bucuresti/calarasi',
'Bucuresti/newyork',
'Bucuresti1',
'Bucuresti5',
'Bucuresti9',
'Bucuresti??',
'Bucurestia',
'Bucurestiaiast',
'Bucurestiborzmatilda',
'Bucurestid',
'Bucurestie',
'Bucurestih',
'Bucurestijmantescu',
'Bucurestil',
'Bucurestim',
'Bucurestima',
'Bucurestimastmar',
'Bucurestimi',
'Bucurestimno',
'Bucurestimu',
'Bucurestin',
'Bucurestip',
'Bucurestir',
'Bucurestiromania',
'Bucurestisi',
'Bucurestisilica.iordache',
'Bucurestistelica',
'Bucurestit',
'Bucurestitu',
'Bucurestiu',
'Bucurestiul',
'Bucurestiului',
'Bucurestivasile.urzica',
'Bucurestivera',
'Bucurestj',
'Bucurestk',
'Bucurestki',
'Bucurestl',
'Bucurestoli',
'Bucurestri',
'Bucureststi',
'Bucurestti',
'Bucurestui',
'Bucuresui',
'Bucureswti',
'Bucuresy',
'Bucuresyi',
'Bucuresyo',
'Bucuresyto',
'Bucuretsi',
'Bucuretsti',
'Bucurewsti',
'Bucurewti',
'Bucurezsti',
'Bucurezti',
'Bucurfesti',
'Bucurfxti',
'Bucuriest',
'Bucuristi',
'Bucurosi',
'Bucurrdti',
'Bucurresti',
'Bucurrstin',
'Bucurseti',
'Bucurssti',
'Bucurstie',
'Bucurtsti',
'Bucuruesti',
'Bucururesti',
'Bucurusti',
'Bucurwsti',
'Bucusesti',
'Bucutesti',
'Bucutresti',
'Bucutrst',
'Bucutrsti',
'Bucuuresti',
'Bucvuresti',
'Bucyresti',
'Bucucresti',
'Bucucuresti',
'Bucueati',
'Bucueesti',
'Bucuersti',
'Bucuesto',
'Bucuharest',
'Bucuirest',
'Bucuiresti',
'Bucuirsti',
'Bucupesti',
'Bucur Esti',
'Bucur3sti',
'Bucuraesti',
'Bucuras',
'Bucurasti',
'Bucure',
'Bucure;ti',
'Bucureasti',
'Bucuredto',
'Bucureesti',
'Bucureist',
'Bucureresti',
'Bucurersti',
'Bucurerti',
'Bucurestizecadumk',
'Bucuretti',
'Bu Curesti',
'Bu Uresti',
'Bu Urezti',
'Bu Urssti',
'Bu8curesti',
'Bubcuresti',
'Bubucresti',
'Buburesti',
'Buc Uresti',
'Bucarest',
'Bucaresti',
'Buccuresti',
'Buucresti',
'Buucuresti',
'Buucurestir',
'Buurestic',
'Buuucuresti',
'Buuuresti',
'Buvcuresti',
'Buvuresti',
'Buvutesti',
'Buxuresi',
'Buxuresti',
'Buycuresti',
'Bucharest Romania',
'Bucharest, Bucurestiromania',
'Bucharest, Rom',
'Buchsrest',
'Buchuresti',
'Buciurest',
'Bucjmuresti',
'Bucruresti',
'Bucharest');

update petitions.petition_signature set city='Timisoara' where city in (
'Timisoata',
'Timisoar',
'Timisora',
'Timsoara',
'Timsoaara',
'Timsioara',
'Timraisoa',
'Timosoara',
'Timiwsoara',
'Timispara',
'Timisosra',
'Timisosda',
'Timisorara',
'Timisor',
'Timisooara',
'Timisoatra',
'Timisoarsa',
'Timisoars',
'Timisoarra',
'Timisoarq',
'Timisoarfa',
'Timisoare',
'Timisoaratudorescu2na@',
'Timisoararadu.nela',
'Timisoaralia',
'Timisoarajoldes.gheorghe@yahoo.com',
'Timisoarai',
'Timisoarac',
'Timisoarab',
'Timisoaraaura_maris',
'Timisoaraana_rachieru@yahoo.com',
'Timisoaraa',
'Timisoara2',
'Timisoara/dumbravita',
'Timisoara, Timis',
'Timisoara, Roumanie',
'Timisoara, Romania',
'Timisoara, Judetul Timis',
'Timisoara Romania',
'Timisoara (romania)',
'Timisoara',
'Timisoaea',
'Timisoaar',
'Timisoaa',
'Timisoa',
'Timiso',
'Timisnoara',
'Timisioara',
'Timisiara',
'Timisara',
'Timisaora',
'Timisaoara',
'Timiosoara',
'Timiosara',
'Timioara',
'Timidoara',
'Timiasoara',
'Timiaora',
'Timiaoara',
'Timi;oara',
'Timi9soara',
'Timi',
'Tiisoara',
'Tiimsoara',
'Tiimisoara',
'Ti Isoara',
'Tmisoara',
'Tmisioara',
'Tm'

);

update petitions.petition_signature set city='Constanta' where city in (
'Costanta'
);

update petitions.petition_signature set city='Baia Mare' where city in (
'Baiamare'
);

update petitions.petition_signature set city='Cluj Napoca' where city in (
'Clujnapoca','Cluj_napoca','Cluj -Napoca','Cluj-N','Cluj - Napoca','Cluj  Napoca','Cluj- Napoca','Cluj','Cluj-Napoca','`cluj-Napoca',
'Clu Napoca',
'Clu-Napoca',
'Club N',
'Club Napoca',
'Clui-Napoca',
'Cluj  - Napoca',
'Cluj -N',
'Cluj / Kolozsvar / Klausenburg',
'Cluj Mapoca',
'Cluj N',
'Cluj N Apoca',
'Cluj N.',
'Cluj Naoca',
'Cluj Naooca',
'Cluj Naouca',
'Cluj Napaca',
'Cluj Napca',
'Cluj Napica',
'Cluj Napo A',
'Cluj Napoa',
'Cluj Napoc',
'Cluj Napoca (transsilvanien)',
'Cluj Napocaa',
'Cluj Napocac',
'Cluj Napocal',
'Cluj Napocan',
'Cluj Napocaov',
'Cluj Napoce',
'Cluj Napocq',
'Cluj Napocs',
'Cluj Napova',
'Cluj Napoxa',
'Cluj Nappca',
'Cluj Naps Ca',
'Cluj Napuca',
'Cluj Nas',
'Cluj Noca',
'Cluj Npoca',
'Cluj Nspoca',
'Cluj Romania',
'Cluj _ Napoca',
'Cluj*napoca',
'Cluj+napoca',
'Cluj, Rom',
'Cluj,-Napoca',
'Cluj,n'
'Cluj,napoca'
'Cluj-',
'Cluj--Napoca',
'Cluj-N.',
'Cluj-Naoca',
'Cluj-Naooca',
'Cluj-Napca',
'Cluj-Napcoa',
'Cluj-Napica',
'Cluj-Napoa',
'Cluj-Napoaca',
'Cluj-Napoc',
'Cluj-Napoca / Kolozsvar / Klausenburg',
'Cluj-Napoca, Cluj',
'Cluj-Napoca, Romania',
'Cluj-Napocaalexandrina.todoran@',
'Cluj-Napocad',
'Cluj-Napocag',
'Cluj-Napocai',
'Cluj-Napocap',
'Cluj-Napoca`',
'Cluj-Napocs',
'Cluj-Napova',
'Cluj-Napoxa',
'Cluj-Napoza',
'Cluj-Nappca',
'Cluj-Nappoca',
'Cluj-Nclujapoca',
'Cluj-Npoca',
'Cluj-Nspoca',
'Cluj.n',
'Cluj.napoca',
'Cluj/n',
'Cluj/napoca',
'Cluj=napoca',
'Clujn Napoca',
'Clujnapocabotezdoru',
'Cluk',
'Cluk Napoca',
'Cluk-Napoca',
'Clul',
'Clul-N',
'Clun-Napoca',
'Cuj - Napoca',
'Cuj Napoca',
'Cuj-Napoca',
'Cum Napoca'
);

update petitions.petition_signature set city='Targu Mures' where city in (
'Tgmures','Tg.-Mures','Tg. Mures','Tg-Mures','Targu-Mures','Tg.mures','Tg Mures','Tirgu-Mures','Tirgu Mures','Tragu-Mures','Tragu Mures','Tg Murs',
'Tg Murex',
'Tg Muress',
'Tg Mures Jud Mures',
'Tg Mure',
'Tg Ms','Tg- Mures',
'Tg,mures',
'Tg, Mures',
'Tg&gt;mures',
'Tg-Mutes',
'Tg-Muresi',
'Tg-Mured','Tg=mures'
'Tg/mures',
'Tg.mures,',
'Tg.mues',
'Tg.mores',
'Tg..- Mures',
'Tg.-Mure;',
'Tg. Murea',
'Tg=mures',
'Tg/mures',
'Tg.mures,',
'Tg.mues',
'Tg.mores',
'Tg..- Mures',
'Tg.-Mure;',
'Tg. Murea'
);

update petitions.petition_signature set city='Drobeta Turnu Severin' where city in (
'Dr.tr Severin',
'Tr.severin','Dr.tr. Severin','Drobeta Tr -Severin','Tr Severin','Drobeta Tr. Severin','Dr-Tr-Severin','Turnu Severin','Drobeta-Turnu-Severin','Drobeta Tr.severin','Drobeta Tr Severin','Dr. Tr. Severin','Drobeta-Turnu Severin','Drobeta Turnu-Severin','Dr.tr.severin','Dr Tr Severin',
'Dr  Tr Severin',
'Dr -Tr-Severin',
'Dr Tr  Severin',
'Dr Tr Deverin',
'Dr Tr Sev',
'Dr Tr Sever4in',
'Dr Tr Severim',
'Dr Tr Sevrin',
'Dr Tr Srverin',
'Dr Tr.severin',
'Dr Traian Severin',
'Dr Trseverin',
'Dr Turnu Severin',
'Dr Turnu-Severin',
'Dr&gt;tr&gt;severin',
'Dr,tr,severin',
'Dr,tr.severin',
'Dr-Tr Severin',
'Dr. Tr Severin',
'Dr. Tr.- Severin',
'Dr. Tr.-Severin',
'Dr. Tr.severin',
'Dr. Tr/ Severin',
'Dr. Turnu Severin',
'Dr.-Tr. Severin',
'Dr.-Tr.-Severin',
'Dr.rr. Severin',
'Dr.tr .severin',
'Dr.tr-Severin',
'Dr.tr.-Severin',
'Dr.trseveri',
'Dr.turnu Severin',
'Dr.turnu-Severin',
'Dr.turnu.severin'
);

update petitions.petition_signature set city='Ramnicu Valcea' where city in (
'Ramicu-Valcea',
'Rm.vilcea',
'Rm.-Valcea',
'Ramnicul Valcea',
'Rm-Valcea',
'Rm Vilcea',
'Rm Valcea',
'Rm. Valcea',
'Rm.valcea',
'Rm. Vilcea',
'Rimnicu Vilcea'
);

update petitions.petition_signature set city='Targu Jiu' where city in (
'Tg-Jiu'
);

update petitions.petition_signature set city='Alba Iulia' where city in (
'Alba-Iulia',
'Alba',
'Alba  Iulia',
'Alba - Iulia',
'Alba -Iulia',
'Alba Ilia',
'Alba Iualia',
'Alba Iuia',
'Alba Iukia',
'Alba Iula',
'Alba Iuli',
'Alba Iulia',
'Alba Iulia Iu',
'Alba Iulian',
'Alba Iulia`',
'Alba Iulie',
'Alba Iuliq',
'Alba Iulis',
'Alba Iulua',
'Alba Lulia',
'Alba Oiulia',
'Alba Oulia',
'Alba Ulia',
'Alba- Iulia',
'Alba-Iulia,romania',
'Alba-Iuliam',
'Alba=iulia',
'Albaiulia',
'Albas Iulia',
'Alba_iulia',
'Aoba Iulia'
);

update petitions.petition_signature set city='Brasov' where city in (
'Bv',
'Braosv',
'Braov',
'Bras0v',
'Brasiov',
'Brasiv',
'Braso',
'Brasob',
'Brasoc',
'Brasoov',
'Brasopv',
'Brasov, Brasov',
'Brasov, Judet Brasov',
'Brasov, Romania',
'Brasov/romania',
'Brasovc',
'Brasovromania',
'Brasovtr',
'Brasovv',
'Braspov',
'Brassov',
'Brasv',
'Brasvo'
);

update petitions.petition_signature set city='Zlatna' where city in (
'Zlatna,jud.alba','Zlatna, Jud. Alba','Zlatna Jud. Alba'
);

update petitions.petition_signature set city='Zarnesti' where city in (
'Zarnesti\\brasov',
'Zarnesti/brasov',
'Zarnesti.brasov',
'Zarnesti-Brasov',
'Zarnesti- Brasov',
'Zarnesti, Brasov',
'Zarnesti Jud. Brasov',
'Zarnesti Jud Brasov',
'Zarnesti Brasov',
'Zarnesti - Brasov',
'Zarnesti (brasov)',
'Zarnesti'
);

update petitions.petition_signature set city='Valul Lui Traian' where city in (
'Valul Lui Traian',
'Valu Traian Constanta',
'Valu Traian',
'Valu Luitraian, Constanta',
'Valu Lui Trian',
'Valu Lui Traian-Constanta',
'Valu Lui Traian- Jud.constanta',
'Valu Lui Traian,ct',
'Valu Lui Traian, Jud. Constanta',
'Valu Lui Traian Jud.constants',
'Valu Lui Traian Constanta',
'Valu Lui Traian - Constanta',
'Valu Lui Traian',
'Valu Lui Taian'
);

update petitions.petition_signature set city='Victoria' where city in (
'Victoria-Bv',
'Victoria-Brasov',
'Victoria-- Brasov',
'Victoria, Bv',
'Victoria Jud.brasovnuticiurea@yahoo.com',
'Victoria Jud.brasov',
'Victoria Brasov',
'Victoria - Brasov',
'Victoria',
'Victori Jud Brasov'
);

update petitions.petition_signature set city='Tirgu Jiu' where city in (
'Tg Ju',
'Tg Jou',
'Tg Jiy',
'Tg Jiu,gorj',
'Tg Jiu',
'Tg Jii',
'Tg Iju',
'Tragu-Jiu',
'Tg-Jyu',
'Tg-Jui',
'Tg-Jiuj',
'Tg-Jiu-Gorj',
'Tg-Ji',
'Tg--Jiu',
'Tg- Jiu',
'Tg,jiu',
'Tg, Jiu'
);


update petitions.petition_signature set city='Balotesti' where city in (
'Balotesti   Ilfov',
'Balotesti -Ilfov',
'Balotesti If',
'Balotesti Ilfov',
'Balotesti Jud Ilfov',
'Balotesti(ilfov)',
'Balotesti, Ilfov',
'Balotesti-Ilfov',
'Balotesti. Ilfov',
'Balotesti/ilfov'
);

update petitions.petition_signature set city='Baicoi' where city in (
'Baicoi   Prahova',
'Baicoi  Jud.  Prahova',
'Baicoi Ph',
'Baicoi, Prahova',
'Baicoi,prahova',
'Baicoi-Ph',
'Baicoi-Prahova',
'Baicoi=prahova'
);

update petitions.petition_signature set city='Baia Mare' where city in (
'Bai Mare',
'Baia   Mare',
'Baia  Mare',
'Baia -Mare',
'Baia ;are',
'Baia Maer',
'Baia Mara',
'Baia Mare',
'Baia Mare          Mm',
'Baia Mare Maramures',
'Baia Mare, 430202',
'Baia Mare, Judetul Maramures',
'Baia Mare, Maramures',
'Baia Mare4',
'Baia Mareica',
'Baia Mareioan',
'Baia Marr',
'Baia Marre',
'Baia Marw',
'Baia Matr',
'Baia Mrar',
'Baia Mre',
'Baia Msre',
'Baia- Mare',
'Baia-Mara',
'Baia-Mare',
'Baia-Mare   Maramures',
'Baia-Matr',
'Baia=mare',
'Baiare Ma',
'Baia_mare',
'Baib-Mare'
);

update petitions.petition_signature set city='Breaza' where city in (
'Breaza , Judetul Prahova',
'Breaza - Prahova',
'Breaza Ph',
'Breaza Prahova',
'Breaza, Prahova',
'Breaza- Prahova',
'Breaza-Prahova',
'Breaza/prahova',
'Breaza_prahova'
);

update petitions.petition_signature set city='Brussels' where city in (
'Bruselles',
'Brusels',
'Brussel',
'Brusseles',
'Brusselles',
'Bruxeelles',
'Bruxel',
'Bruxeles',
'Bruxell',
'Bruxelle',
'Bruxelled',
'Bruxelles',
'Bruxelles 5',
'Bruxelless',
'Bruxells'
);

update petitions.petition_signature set city='Borsa' where city in (
'Borsa',
'Borsa  Mm',
'Borsa , Maramures',
'Borsa Maramures',
'Borsa Mm',
'Borsa, Maramures',
'Borsa,maramures',
'Borsa,mm',
'Borsa-Maramures',
'Borsa...maramures'
);

update petitions.petition_signature set city='Campulung Moldovenesc' where city in (
'C Lung Mold',
'C Lung Moldovenesc',
'C-Lumg Mold',
'C-Lung Mold.',
'C-Lung Moldovenesc',
'C-Lung-Moldovenesc',
'C-Lung. Mold',
'C-Lung. Moldovenesc',
'C-Lung.mold.',
'C.lung Moldovenesc',
'C.lung.moldovenesc',
'Cimpulung Mold',
'Cimpulung Mold.',
'Cimpulung Moldovenesc',
'Cimpulung-Moldovenesc',
'Cimpulungmoldovenesc',
'Campukung Moldovenesc',
'Campuling Moldovenesc',
'Campulun Moldovenesc',
'Campulung  Mold',
'Campulung  Moldovenesc',
'Campulung Mo0ldovenesc',
'Campulung Mold',
'Campulung Mold.',
'Campulung Moldovenec',
'Campulung Moldovenes',
'Campulung Moldovenesc Suceava',
'Campulung Moldovenessc',
'Campulung Moldovenesx',
'Campulung Moldovenrsc',
'Campulung Moldovnesc',
'Campulung Moldovnesc Jud.suceava',
'Campulung Moldovrnesc',
'Campulung-M.',
'Campulung-Moldovenesc'
);

update petitions.petition_signature set city='Codlea' where city in (
'Codlea , Brasov',
'Codlea ,brasov',
'Codlea Brasov',
'Codlea Bv',
'Codlea Jud Brasov',
'Codlea Judetul Brasov',
'Codlea, Brasov',
'Codlea, Jud. Brasov',
'Codlea, Judetul Brasov',
'Codlea-Brasov',
'Codleada'
);

update petitions.petition_signature set city='Constanta' where city in (
'Constants',
'Constantu',
'Constany',
'Constata',
'Constatan',
'Constnata',
'Constnta',
'Constranta',
'Constsnta',
'Constsnts',
'Consttanta',
'Contanta',
'Connstanta',
'Cons',
'Consanta',
'Consatnta',
'Consdtanta',
'Consta',
'Constaanta',
'Constabta',
'Constamta',
'Constan',
'Constan\'a',
'Constana',
'Constanata',
'Constanra',
'Constant',
'Constanta .',
'Constanta Cornel Costea',
'Constanta, Constanta',
'Constanta, Romania',
'Constantac',
'Constantaenachevas',
'Constantaflorindmanea@gmail.com',
'Constantagfrusina',
'Constantanta',
'Constantaq',
'Constantar',
'Constanta`',
'Conztanta',
'Coonstanta',
'Cponstanta'
);

update petitions.petition_signature set city='Craiova' where city in (
'Craiiova',
'Craiiva',
'Craio0va',
'Craioa',
'Craioav',
'Craioava',
'Craioba',
'Craioca',
'Craiocva',
'Craioiva',
'Craioma',
'Craiov',
'Craiova   Dolj',
'Craiova Elenadumitrescu',
'Craiova, 200640',
'Craiova, Dolj',
'Craiova, Judetul Dolj',
'Craiova,dolj',
'Craiova-Dolj',
'Craiovaa',
'Craiovac',
'Craiovadsiagicasfj',
'Craiovall',
'Craiovas',
'Craiovastr.amilcarsandulescu 5',
'Craiovba',
'Craiovs',
'Craivoa',
'Crajova',
'Craova',
'Craqiova',
'Cratova',
'Criova',
'Crsiova',
'Crsiovs'
);



update petitions.petition_signature set city='Curtea De Arges' where city in (
'Currea De Arges',
'Curte De Arges',
'Curtea',
'Curtea  De  Arges',
'Curtea De A Rges',
'Curtea De Ages',
'Curtea De Ares',
'Curtea De Arged',
'Curtea De Arges, Jud. Arges',
'Curtea De Argesii',
'Curtea De Argez',
'Curtea De Argrges',
'Curtea Dearges',
'Curtea Vde Arges',
'Curtea-De-Arges',
'Curtea. Dearges',
'Curteade Arges',
'Cutea De Arges');

update petitions.petition_signature set city='Piatra Neamt' where city in (
'Piatra_neamt',
'Piatraneamt',
'Piatraa Neamt',
'Piatra/neamt',
'Piatra-Nemt',
'Piatra-Neamt',
'Piatra-Namt',
'Piatra- Neamt',
'Piatra Niamt',
'Piatra Newamt',
'Piatra Nemt',
'Piatra Nemat',
'Piatra Neeamt',
'Piatra Neant',
'Piatra Neamtpr',
'Piatra Neamta',
'Piatra Neamt, Neamt',
'Piatra Neamt Jud. Neamt',
'Piatra Neamr',
'Piatra Neamnt',
'Piatra Neam',
'Piatra Naemt',
'Piatra Meamt',
'Piatra Eamt',
'Piatra -Neamt',
'Piatra - Neamt',
'Piatra  Neamt',
'Piatra   Neamt',
'Piatra',
'Piatr Neamt',
'Piatea Neamt',
'Piata Neamt'
);

update petitions.petition_signature set city='Pitesti' where city in (
'Pitsti',
'Pitssti',
'Pitseti',
'Pitrsti',
'Pitezti',
'Piteti',
'Pitesyi',
'Pitestu',
'Pitesto',
'Pitestiu',
'Pitestipitesti',
'Pitestie',
'Pitesti.',
'Pitesti-Arges',
'Pitesti, Arges',
'Pitesti\'',
'Pitesti Romania',
'Pitesti Arges',
'Pitest',
'Pitesri',
'Pitesi',
'Pitesfi',
'Pites',
'Pitedto',
'Piteati'
);

update petitions.petition_signature set city='Ploiesti' where city in (
'Plooesti',
'Ploisti',
'Ploirsti',
'Ploietti',
'Ploieti',
'Ploiestyi',
'Ploiestu',
'Ploiesto',
'Ploiesti`',
'Ploiestisi',
'Ploiestir',
'Ploiestiori',
'Ploiestio',
'Ploiestii',
'Ploiesticom',
'Ploiestib',
'Ploiestiaurelia.petre',
'Ploiesti2',
'Ploiesti-Prahova',
'Ploiesti,prahova',
'Ploiesti, Romania',
'Ploiesti, Prahova',
'Ploiesti - Prahova',
'Ploiest8',
'Ploiest',
'Ploiesri',
'Ploiesi',
'Ploiescti',
'Ploies',
'Ploiersti',
'Ploiedti',
'Ploieati',
'Ploieasti',
'Ploie;ti',
'Ploiasti',
'Ploi',
'Ploesti',
'Ploeisti',
'Plioesti',
'Pliesti'
);

update petitions.petition_signature set city='Phoenix' where city in (
'Phoenx',
'Phoeniz',
'Phoenix,arizona',
'Phoenix, Az',
'Phoenix, Arizona',
'Phoenix Az',
'Phoenix Arizona',
'Phoenix ,az.',
'Phoenix , Az',
'Phoebix,az',
'Pheonix',
'Phenix - Arizona');

update petitions.petition_signature set city='Popesti Leordeni' where city in (
'Popestileordeni',
'Popesti-Leordenimargaretacarabageac#@@',
'Popesti-Leordenibucuresti, Sector4',
'Popesti-Leordeni, Ilfov',
'Popesti-Leordeni Ilfov',
'Popesti-Leordeni',
'Popesti-Leorden',
'Popesti-Leordemi',
'Popesti-Leoddeni',
'Popesti-Leirdeni',
'Popestileordeni',
'Popesti-Leordenimargaretacarabageac#@@',
'Popesti-Leordenibucuresti, Sector4',
'Popesti-Leordeni, Ilfov',
'Popesti-Leordeni Ilfov',
'Popesti-Leordeni',
'Popesti-Leorden',
'Popesti-Leordemi',
'Popesti-Leoddeni',
'Popesti-Leirdeni',
'Popesti- Leordeni',
'Popesti Lrordeni',
'Popesti Loerdeni',
'Popesti Leordeni-Ilfov',
'Popesti Leordeni Ilfov',
'Popesti Leordeni - Ilfov',
'Popesti Leoedeni',
'Popesti Leirdeni',
'Popesti -Leordeni',
'Popesti - Leordeni',
'Popesti + Leordeni',
'Pop. Leordeni',
'Pop Leordeni');

update petitions.petition_signature set city='Roman' where city in (
'Roman/neamt',
'Roman-Neamt',
'Roman-Jud.neamt',
'Roman,neamt',
'Roman,jud.neamt',
'Roman, Romania',
'Roman, Neamt',
'Roman, Jud.neamt',
'Roman \\ Neamt',
'Roman Neamt',
'Roman Jud.neamt',
'Roman Jud Neamt',
'Roman , Neamt',
'Roman  Neamt');

update petitions.petition_signature set city='Rosiorii De Vede' where city in (
'Rosiroi De Vede',
'Rosiorii-De - Vede',
'Rosiorii+de Vede',
'Rosiorii De Vedr',
'Rosiorii De Vede . Jud. Teleorman',
'Rosiorii De Ved',
'Rosiorii -De-Vede',
'Rosiori-De-Vede',
'Rosiori Vede',
'Rosiori Devede',
'Rosiori De Vede',
'Rosiori  De Vede'
);

update petitions.petition_signature set city='Tarnaveni' where city in (
'Tarnavni Ju.mures',
'Tarnaveni, Mures',
'Tarnaveni Jud.murea',
'Tirnaveni/mures',
'Tirnaveni');

update petitions.petition_signature set city='Turnu Magurele' where city in (
'Turnumagurele',
'Turnu=magurele',
'Turnu-Magurele',
'Turnu- Magurele',
'Turnu Mgurele',
'Turnu Magurle',
'Turnu Magurelr',
'Turnu Magurele, Teleorman',
'Turnu Magurele Jud Teleorman',
'Turnu Maguele');

update petitions.petition_signature set city='Valenii De Munte' where city in (
'Valentin De Munte',
'Valeniu De Munte',
'Valeniide Munte',
'Valenii-De-Munte',
'Valenii De Muntr',
'Valenii De Munte-Prahova',
'Valenii De Munte,ph',
'Valenii De Munte,jud. Ph',
'Valenii De Munte, Jud. Ph',
'Valenii De Munte Prahova',
'Valenii De Munte - Prahova',
'Valenii De Munte  Prahova',
'Valenii  De Munte',
'Valeni De Munte,prahova',
'Valeni De Munte');

update petitions.petition_signature set city='Vatra Dornei' where city in (
'Vatradornei',
'Vatra-Dornei',
'Vatra Drornei',
'Vatra Dronei',
'Vatra Dorni',
'Vatra Dorneia',
'Vatra -Dornei',
'Vatra - Dornei',
'Vatra  Dornei');



update petitions.petition_signature set city='Botosani' where city in (
'Botoani',
'Botoasani',
'Botosabi',
'Botosai',
'Botosami',
'Botosan',
'Botosana',
'Botosani',
'Botosani (bt)',
'Botosaniatitieneisi',
'Botosanie',
'Botosanielenaromanelena',
'Botosanio',
'Botosaniu',
'Botosank',
'Botosano',
'Botosanu',
'Botosni',
'Bototani',
'Bototsani',
'Botsani');

update petitions.petition_signature set city='Bragadiru' where city in (
'Bragadiru',
'Bragadiru - Ilfov',
'Bragadiru, Ilfov',
'Bragadiru-If',
'Bragadiru-Ilfov',
'Bragadiru/ilfov',
'Bragadoru');



update petitions.petition_signature set city='Boldesti Scaieni' where city in (
'Boldessti-Scaeni',
'Boldesti  Scaeni',
'Boldesti Scaeni',
'Boldesti Scaini',
'Boldesti- Scaeni',
'Boldesti- Scaeni, Jud. Prahova',
'Boldesti-Scaeni',
'Boldesti-Scaeni (prahova)',
'Boldesti-Scaieni',
'Boldesti-Scaieni, Jud Ph',
'Boldesti-Scaieni,prahova',
'Boldesti_scaeni');



update petitions.petition_signature set city='Munich' where city in ('Munchen','Munichen');

update petitions.petition_signature set city='Sebes' where city in (
'Sebe',
'Sebed',
'Sebee',
'Sebes  Alba',
'Sebes , Jud. Alba',
'Sebes Alba',
'Sebes Jud Alba',
'Sebes Jud. Alba',
'Sebes, Alba Iulia',
'Sebes, Jud.alba',
'Sebes,alba',
'Sebes- Alba',
'Sebes-Alba');

update petitions.petition_signature set city='Slatina' where city in (
'Slatina    Jud.olt',
'Slatina   Olt',
'Slatina  Olt',
'Slatina ,olt',
'Slatina - Olt',
'Slatina Olt',
'Slatina, Olt',
'Slatina, Olt, Romania',
'Slatina, Olt.',
'Slatina,olt',
'Slatina- Olt',
'Slatina----Olt',
'Slatina-Olt',
'Slatina-Olt.',
'Slatinaa');

update petitions.petition_signature set city='Sibiu' where city in (
'Siubiu',
'Sivbiu',
'Siviu',
'Sibbiu',
'Sibi',
'Sibih',
'Sibii',
'Sibiiu',
'Sibiu Mitica1941@gmail.com',
'Sibiu, Sibiu County',
'Sibiu, Str. A.saguna, Nr.8',
'Sibiui',
'Sibuu');

update petitions.petition_signature set city='Sighetu  Marmatiei' where city in (
'Sighet Marmatie',
'Sighet, Mm',
'Sighetu -Marmatiei',
'Sighetu M',
'Sighetu M.',
'Sighetu Maramatiei',
'Sighetu Marmati',
'Sighetu Marmatie',
'Sighetu Marmatiei',
'Sighetu Marmatieiocluzie@',
'Sighetu-M',
'Sighetu-M.',
'Sighetu-Marmatiei',
'Sighetu-Matmatiei',
'Sighetu-Msrmatiei',
'Sighetul M.',
'Sighetul Marm.',
'Sighetul Marmatiei',
'Sighetul-Marmatiei',
'Sighetumarmatiei');

update petitions.petition_signature set city='Sebis' where city in (
'Sebis Jud. Arad',
'Sebis Judetul Arad',
'Sebis, Arad',
'Sebis, Jud Ard',
'Sebis, Jud.arad',
'Sebis-Ar');




















